Adicionando gerador de yaml de imagens locais
tribeiro/t80s_reduce pull request #1
Opened 2016-09-30 13:52 UTC by duducosmos

2016-10-04 11:34 UTC, tribeiro commented on t80s_reduce/t80s_gen_download/main.py
> +
In this package I have not used this style for calling the scripts. Instead I create a "__main__.py" which is responsible for calling the main function. This way you can call the package name directly from python to run the script. 

So, remove the following lines.

2016-10-04 11:34 UTC, tribeiro commented on t80s_reduce/t80s_sort_night/main.py
> +if(__name__ == "__main__"):
same as in t80s_gen_download. Remove the following lines.

2016-10-04 11:34 UTC, tribeiro commented on t80s_reduce/t80s_sort_night/new.yaml
> +night: '2016927'
This configuration file should not be included in the repository. Please, remove it.

2016-10-04 11:34 UTC, tribeiro commented on t80s_reduce/t80s_sort_night/sort_night_files.py
> +if(__name__ == "__main__"):
This needs to be worked out a little bit, but the overall code is pretty neat. Let's review it latter, once we go through the basic stuff.

2016-10-04 11:34 UTC, tribeiro commented on t80s_reduce/t80s_sort_night/sort_night_files_test.py
> +#!/usr/bin/env python
Maybe this would be better in a test directory elsewhere. Maybe create a directory under t80s_reduce/tests/ and move it there.

2016-10-04 11:34 UTC, tribeiro commented on t80s_reduce/t80s_sort_night/teste.yaml
> +night: '2016927'
Another yaml configuration file that should not be part of the commit. Please, remove it.

2016-10-05 19:08 UTC, duducosmos commented
Correction from the sugestion of the last PR

2016-10-05 19:46 UTC, tribeiro requested changes
Hy Eduardo, 

please exclude the file 

t80s_reduce/t80s_sort_night/sort_night_files.pyc 

from the commit as well.

2016-10-05 19:58 UTC, tribeiro approved these changes

2016-10-05 19:59 UTC, merged